Fix cyclic dependency
Pante/elementary pull request #150
Opened 2022-10-15 15:50 UTC by CC007

Elementary depends on Utilitary, but Utilitary's tests also depended on Elementary. This cyclic dependency caused issues when building and testing. Furthermore, this test dependency referred to an older version of Elementary, which caused junit dependency mismatch issues.

All this is now solved by introducing a new itest module for all tests in Utilitary that depended on Elementary.

Signed-off-by: CC007 <Coolcat_the_best2@Hotmail.com>

2022-10-16 03:36 UTC, Pante reviewed
Thanks for the PR! I think moving the tests into a separate module is a good way to break the cyclic dependencies. However, I don't think `itest`/integration tests is a good way to describe the tests. They are unit tests for utilitary after all.

2022-10-16 08:46 UTC, CC007 commented
They aren't really unit tests. Though, because you aren't really testing the unit by itself (which would be hard given the limitations of compiler testing). You're testing it's use when integrated with the elementary ToolsExtension.

2022-10-16 11:01 UTC, Pante commented
Hmm fair enough

2022-10-18 07:45 UTC, Pante requested changes
LGTM, just two minor nitpicks. Thanks for taking the time to submit a PR!

2022-10-18 07:45 UTC, Pante commented on utilitary-itest/pom.xml
> +    <description>The integration test module for testing the Utilitary module.</description>
Nitpick: I think the description can be better phrased as "Integration tests for Utilitary."

2022-10-18 07:45 UTC, Pante commented on utilitary-itest/pom.xml
> +    <name>Utilitary integration test</name>
Nit[ick: I think it should be "Utilitary Integration Tests".

2022-10-18 09:16 UTC, CC007 commented on utilitary-itest/pom.xml
> +    <name>Utilitary integration test</name>
@Pante you can also add suggestions like so:
```suggestion
    <name>Utilitary Integration Tests</name>
```

2022-10-18 09:17 UTC, CC007 commented on utilitary-itest/pom.xml
> +    <description>The integration test module for testing the Utilitary module.</description>
```suggestion
    <description>Integration tests for Utilitary.</description>
```

2022-10-18 09:21 UTC, Pante commented on utilitary-itest/pom.xml
> +    <name>Utilitary integration test</name>
Ohhh, that’s really neat, I never knew that feature existed.

2022-10-18 09:22 UTC, Pante approved these changes

2022-10-18 09:22 UTC, merged

2022-10-18 18:05 UTC, Pante commented
Yup, I’m going to disable codecov altogether soon