Fix that modules can't be compiled with elementary
Pante/elementary pull request #152
Opened 2022-10-15 16:21 UTC by CC007

The URI.create call in the MemoryFileManager expected a valid URI, but location.getName() returned illegal URI characters. This has now been fixed by URL encoding location.getName()

Signed-off-by: CC007

2022-10-16 03:18 UTC, Pante requested changes
Thanks for creating this PR! I think the it looks good in general, just a few style & minor issues. Also, think adding a test case for when the location name contains invalid/illegal characters will be nice.

2022-10-16 03:18 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +import java.nio.charset.StandardCharsets;
In general, we prefer star imports when possible.

2022-10-16 03:18 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
In general, we prefer `var` (doesn't have to be final) when possible.

2022-10-16 03:18 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
I don't think `StandardCharsets.UTF_8` needs to be converted into a string as there's an [overload](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URLEncoder.html#encode(java.lang.String,java.nio.charset.Charset)) for `CharSet`,

2022-10-16 03:18 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            throw new RuntimeException(e);
I think throwing an `UncheckedIOException` will be better in this case.

2022-10-16 03:18 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +        }
The same comments for lines 51 to 56 above applies to this method as well.

2022-10-16 09:04 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +import java.nio.charset.StandardCharsets;
Considering the following:
 - https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad
 - https://rules.sonarsource.com/java/RSPEC-2208

It's usually better to avoid star imports for cleaner, less error-prone code.

2022-10-16 09:10 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
I agree that when using an IDE with type analysis, like IntelliJ, there definitely are benefits to using `var`, but when doing code reviews github/gitlab/bitbucket don't show this inferred type, so it could make verifying the validity of methods using `var` harder, as you might be getting a different type than you expect.

2022-10-16 10:31 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
Ah, I see they added it in Java 10

2022-10-16 10:48 UTC, CC007 commented
> Thanks for creating this PR! I think the it looks good in general, just a few style & minor issues. Also, think adding a test case for when the location name contains invalid/illegal characters will be nice.

Added

2022-10-16 11:05 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +import java.nio.charset.StandardCharsets;
I disagree with the "cluttering" argument, the most often cited example is the conflict between `java.awt.List` and `java.util.List`. However, it is the exception rather than the norm. In most cases, it's far more concise to use start imports. IMO, it's far better to use star imports and fall back to singular imports in the rare case that a conflict occurs.

2022-10-16 11:09 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
Personally, I don't find it that big of an issue since the type isn't that important in most cases and we can (at least if done properly) infer the type from the method. Also, I do perform most of my reviews in IntelliJ which allows me to easily jump about :P.

2022-10-16 15:41 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
Yea, for personal projects that I'm the only dev on I usually also prefer using var. Just wanted to share this point of view. Anyway, since you preferred it I changed it to var

2022-10-16 15:43 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            throw new RuntimeException(e);
I agree, but it's a moot point now that I use Charset as a parameter, rather than String, so the whole try-catch is gone now.

2022-10-16 15:43 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
Fixed

2022-10-16 15:55 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +import java.nio.charset.StandardCharsets;
It also happen a lot with `java.sql.Date` and `java.util.Date` or with mappers in REST controllers, where the DTO class gets converted to the internal model class and/or to the DTOs used for outgoing REST calls. 

I don't think it's always a problematic enough to remove any star import I see, but I'm not going to explicitly change my default editor settings so that it forces star imports when only 2 imports share the same package. When using any modern IDE the imports will be hidden anyway, so what does it matter, right?

If you do mind it that much, feel free to add a pre-commit hook so that contributors don't have to worry about these things.

2022-10-16 15:55 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +            final String locationName = URLEncoder.encode(location.getName(), StandardCharsets.UTF_8.toString());
Yup, all good ^^ thanks

2022-10-16 15:58 UTC, CC007 commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +        }
fixed

2022-10-17 02:30 UTC, Pante commented on elementary/src/main/java/com/karuslabs/elementary/file/MemoryFileManager.java
> +import java.nio.charset.StandardCharsets;
I'll probably do what we did internally at Forus Labs which is to add a GitHub Action that automatically formats the code and commits it in the near future. But for now, I'll just approve the PR and manually format the imports.

2022-10-17 02:30 UTC, Pante approved these changes

2022-10-17 02:31 UTC, merged